---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "config/hosts.yaml"
    group_file: "config/groups.yaml"
runner:
  plugin: threaded
  options:
    num_workers: 10
logging:
  enabled: False
